### ISSUE TITLE
What should I do?

### ISSUE THREAD

**Issue by julian0830** [U7P4L-IN/NUMBER-INFO#5]
I try to run the application after installing all the plugins and extras and it gives me this error
Traceback (most recent call last):
  File "/sdcard/p-Enc.py", line 9, in <module>
  File "<string>", line 1, in <module>
  File "<x>", line 1, in <module>
  File "<x>", line 1, in <module>
  File "<x>", line 1, in <module>
  File "<x>", line 1, in <module>
  File "<x>", line 9, in <module>
ModuleNotFoundError: No module named 'phonenumbers'

**Comment by U7P4L-IN** [comment]
Install module "pip install phonenumbers"

**Comment by julian0830** [comment]
> Install module "pip install phonenumbers"

Thanks
