### ISSUE TITLE
Invalid country code

### ISSUE THREAD

**Issue by drybonesification** [U7P4L-IN/NUMBER-INFO#6]
May not be an issue with your side but it spits out:
`
Traceback (most recent call last):
  File "/sdcard/p-Enc.py", line 9, in <module>
  File "<string>", line 1, in <module>
  File "<x>", line 1, in <module>
  File "<x>", line 1, in <module>
  File "<x>", line 1, in <module>
  File "<x>", line 1, in <module>
  File "<x>", line 221, in <module>
  File "<x>", line 84, in menu
  File "<x>", line 116, in number_info
  File "/usr/lib/python3/dist-packages/phonenumbers/phonenumberutil.py", line 2927, in parse
    raise NumberParseException(NumberParseException.INVALID_COUNTRY_CODE,
phonenumbers.phonenumberutil.NumberParseException: (0) Missing or invalid default region.
`

**Comment by U7P4L-IN** [comment]
Install module
